name: speed-test
version: master
summary: Test your internet connection speed and ping from the CLI
description: |
  Test your internet connection speed and ping using speedtest.net from the CLI

grade: stable
confinement: strict

apps:
  speed-test:
    command: speed-test
    plugs: [network]

parts:
  speed-test:
    source: .
    plugin: nodejs
